.TH "admin_login.h" 3 "Tue Apr 21 2020" "Electronic_Polling_System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
admin_login.h \- Implementation of admin login function for access to the system\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBadmin_login\fP ()"
.br
.RI "This function is to authenticate admin into the system\&. "
.in -1c
.SH "Detailed Description"
.PP 
Implementation of admin login function for access to the system\&. 


.PP
\fBAuthor\fP
.RS 4
vignesh balaji - vigneshbalaji@cmail.carleton.ca 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int admin_login ()"

.PP
This function is to authenticate admin into the system\&. This function compares the input(i\&.e Admin-ID and PAssword) given by the Admin\&.when the comparison gets successful the output will display as Welcome\&.Login success!
.PP
\fBParameters\fP
.RS 4
\fIIt\fP takes the Admin-ID, Password and File name as the input parameter\&.
.RE
.PP
\fBReturns\fP
.RS 4
Return 0 on successful login and 1 if login failed\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Electronic_Polling_System from the source code\&.
