.TH "candidate_details.h" 3 "Tue Apr 21 2020" "Electronic_Polling_System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
candidate_details.h \- Implementation of candidate_details function to display the candidates contesting in a particular province\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBcandidate_details\fP (char *province, char *username)"
.br
.RI "The function displays a list of candidates present in the file\&. "
.in -1c
.SH "Detailed Description"
.PP 
Implementation of candidate_details function to display the candidates contesting in a particular province\&. 


.PP
\fBAuthor\fP
.RS 4
Priyanga Soundararajan - priyangasoundararaja@cmail.carleton.ca 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int candidate_details (char * province, char * username)"

.PP
The function displays a list of candidates present in the file\&. 
.PP
\fBParameters\fP
.RS 4
\fIThe\fP function takes “province” as input parameter\&.
.br
\fIThe\fP function displays candidate details in the logged in user's province
.RE
.PP
\fBReturns\fP
.RS 4
Return 0 when entered province is valid else return 1 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Electronic_Polling_System from the source code\&.
