.TH "display_count.h" 3 "Tue Apr 21 2020" "Electronic_Polling_System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
display_count.h \- Implementation of display_count function to display the final count of the votes casted\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBdisplay_count\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implementation of display_count function to display the final count of the votes casted\&. 


.PP
\fBAuthor\fP
.RS 4
Priyanga Soundararajan - priyangasoundararaja@cmail.carleton.ca 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int display_count ()"
The function displays a final cont of the votes present in the file\&. 
.PP
\fBParameters\fP
.RS 4
\fIthe\fP function takes “filename” as input parameter\&.
.br
\fIthe\fP function displays the 'vote_count\&.csv' file as the output\&.
.RE
.PP
\fBReturns\fP
.RS 4
Return 0 when file opens and return 1 when filename is invalid\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Electronic_Polling_System from the source code\&.
