.TH "function.h" 3 "Tue Apr 21 2020" "Electronic_Polling_System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
function.h \- Simply contains all the headers of the different function to make main\&.c file cleaner\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'admin_login\&.h'\fP
.br
\fC#include 'user_login\&.h'\fP
.br
\fC#include 'user_details\&.h'\fP
.br
\fC#include 'candidate_details\&.h'\fP
.br
\fC#include 'replace_char\&.h'\fP
.br
\fC#include 'get_field\&.h'\fP
.br
\fC#include 'get_file_column_size\&.h'\fP
.br
\fC#include 'int_to_string\&.h'\fP
.br
\fC#include 'cast_vote\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBitoa\fP(x)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Simply contains all the headers of the different function to make main\&.c file cleaner\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define itoa(x)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Electronic_Polling_System from the source code\&.
