.TH "get_file_column_size.h" 3 "Tue Apr 21 2020" "Electronic_Polling_System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
get_file_column_size.h \- Implementation of getting a CSV file column size\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBget_file_column_size\fP (char *tmp)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implementation of getting a CSV file column size\&. 


.PP
\fBAuthor\fP
.RS 4
Priyanga Soundararajan-priyangasoundararaja@cmail.carleton.ca 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int get_file_column_size (char * tmp)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Electronic_Polling_System from the source code\&.
