.TH "int_to_string.h" 3 "Tue Apr 21 2020" "Electronic_Polling_System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
int_to_string.h \- Implementation of intToString function to convert int to string\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBint_to_string\fP (int num, char *str)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implementation of intToString function to convert int to string\&. 


.PP
\fBAuthor\fP
.RS 4
Priyanga Soundararajan - priyangasoundararaja@cmail.carleton.ca 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "char* int_to_string (int num, char * str)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Electronic_Polling_System from the source code\&.
