.TH "replace_char.h" 3 "Tue Apr 21 2020" "Electronic_Polling_System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
replace_char.h \- Implementation of replacing a character with other\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBreplace_char\fP (char *str, char find, char replace)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implementation of replacing a character with other\&. 


.PP
\fBAuthor\fP
.RS 4
Priyanga Soundararajan-priyangasoundararaja@cmail.carleton.ca 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "char* replace_char (char * str, char find, char replace)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Electronic_Polling_System from the source code\&.
